// <auto-generated />
using DI.DataPersistant.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DI.DataPersistant.Migrations
{
    [DbContext(typeof(DataModel))]
    [Migration("20180129032258_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DI.Domain.Entity.CarImage", b =>
                {
                    b.Property<int>("CarImageId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CarTypeId");

                    b.Property<string>("Name");

                    b.HasKey("CarImageId");

                    b.HasIndex("CarTypeId");

                    b.ToTable("CarImage");
                });

            modelBuilder.Entity("DI.Domain.Entity.CarType", b =>
                {
                    b.Property<int>("CarTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("CarTypeId");

                    b.ToTable("CarType");
                });

            modelBuilder.Entity("DI.Domain.Entity.CarImage", b =>
                {
                    b.HasOne("DI.Domain.Entity.CarType", "CarType")
                        .WithMany("CarImages")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
